import { createContext, useContext, useState } from "react";
const CurrenciesContext = createContext();

export const CurrenciesProvider = ({ children }) => {
  const [ownedCurrencies, setOwnedCurrencies] = useState([
    { name: "tether", ownedAmount : 1000},
  ]);
  const safeSetOwnedCurrencies = (updater) => { // generated by chatgpt beacause if you filter when ever the ownedcurrency change with its own setter then an infinte loop will happen
    setOwnedCurrencies((prev) => {
      const updated = typeof updater === "function" ? updater(prev) : updater;
      // 🔹 Filter out currencies with zero or NaN ownedAmount
      return updated.filter((c) => (Number(c.ownedAmount) || 0) > 0);
    });
}

  return (
    <CurrenciesContext.Provider value={{ ownedCurrencies, setOwnedCurrencies : safeSetOwnedCurrencies }}>
      {children}
    </CurrenciesContext.Provider>
  );
};
export const useCurrencies = () => useContext(CurrenciesContext);